version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 40
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.18
    - 5.11.9
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
    - 1.3.9
  - dependency-name: helmet
    versions:
    - 4.3.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: axios
    versions:
    - 0.21.0
  - dependency-name: webpack
    versions:
    - 4.44.2
  - dependency-name: css-loader
    versions:
    - 4.3.0
  - dependency-name: webpack-merge
    versions:
    - 5.1.4
  - dependency-name: eslint-loader
    versions:
    - 3.0.4
  - dependency-name: node-sass
    versions:
    - 4.14.1
  - dependency-name: eslint
    versions:
    - 5.16.0
